In [82]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import patsy
import statsmodels.api as sm
import scipy.stats as stats

In [83]:
df = pd.read_csv('awards.csv')

In [98]:
actor_awards = df.loc[((df['Award'] == "Actor") | (df['Award'] == "Actress") | (df['Award'] == "Actor in a Supporting Role") | (df['Award'] == "Actress in a Supporting Role"))]

actor_awards = actor_awards.drop(["Name", "Year", "Ceremony"], axis=1)
actor_awards.fillna(0, inplace=True)

In [103]:
awards_df = pd.DataFrame(columns=["Film", "Nominated Actor", "Actor", "Actress", "Supporting Actor", "Supporting Actress"])
awards_df["Film"] = actor_awards["Film"].unique()
awards_df["Nominated Actor"] = 1
awards_df.fillna(0, inplace=True)

# Keeping a copy so we can see who was nominated 
nominations = actor_awards.copy(deep=True)

# Uniuqie movies in the dataframe 
#total_movies = df["Film"].unique()

# I think this is trying to get the unique movies that were nominated for acting awards?
winners = actor_awards[actor_awards["Winner"] == 1.0]
arr_film_one = []
for i in range(0,actor_awards.shape[0]):
    try:
        if actor_awards[i] not in arr_film_one:
            arr_film_one.append(actor_awards[i])
    except KeyError:
        pass
    

# I think this is trying to get the unique movies that were NOT nominated for acting awards?
arr_film_zero = list(arr_film_one)
for i in range(0,len(total_movies)):
    if total_movies[i] not in arr_film_zero:
        arr_film_zero.append(total_movies[i])
        
actor_awards.set_index('Film',inplace=True)
awards_df.set_index('Film',inplace=True)

for index, row in actor_awards.iterrows():
    if(row["Award"] == "Actor"):
        awards_df.loc[index, "Actor"] = row["Winner"]
    elif(row["Award"] == "Actress"):
        awards_df.loc[index, "Actor"] = row["Winner"]
    elif(row["Award"] == "Supporting Actor"):
        awards_df.loc[index, "Actor"] = row["Winner"]
    elif(row["Award"] == "Support Actress"):
        awards_df.loc[index, "Actor"] = row["Winner"]

actor_awards.reset_index(inplace=True)
awards_df.reset_index(inplace=True)

awards_df

,Film,Nominated Actor,Actor,Actress,Supporting Actor,Supporting Actress
0,The Noose,1,0.0,0,0,0
1,The Last Command,1,1.0,0,0,0
2,A Ship Comes In,1,0.0,0,0,0
3,7th Heaven,1,1.0,0,0,0
4,Sadie Thompson,1,0.0,0,0,0
5,Thunderbolt,1,0.0,0,0,0
6,In Old Arizona,1,1.0,0,0,0
7,Alibi,1,0.0,0,0,0
8,The Valiant,1,0.0,0,0,0
9,The Patriot,1,0.0,0,0,0
10,Madame X,1,0.0,0,0,0
11,The Barker,1,0.0,0,0,0
12,The Letter,1,0.0,0,0,0
13,The Divine Lady,1,0.0,0,0,0
14,The Broadway Melody,1,0.0,0,0,0
15,Coquette,1,1.0,0,0,0
16,Disraeli,1,1.0,0,0,0
17,The Green Goddess,1,0.0,0,0,0
18,The Big House,1,0.0,0,0,0
19,The Big Pond,1,0.0,0,0,0
20,Bulldog Drummond,1,0.0,0,0,0
21,The Rogue Song,1,0.0,0,0,0
22,The Devil's Holiday,1,0.0,0,0,0
23,Sarah and Son,1,0.0,0,0,0
24,Anna Christie,1,0.0,0,0,0
25,The Divorcee,1,1.0,0,0,0
26,Their Own Desire,1,0.0,0,0,0
27,The Trespasser,1,0.0,0,0,0
28,A Free Soul,1,0.0,0,0,0
29,Skippy,1,0.0,0,0,0
...,...,...,...,...,...,...
865,The Master,1,0.0,0,0,0
866,Lincoln,1,0.0,0,0,0
867,Django Unchained,1,0.0,0,0,0
868,Les Misérables,1,0.0,0,0,0
869,The Sessions,1,0.0,0,0,0
870,Captain Phillips,1,0.0,0,0,0
871,American Hustle,1,0.0,0,0,0
872,12 Years a Slave,1,0.0,0,0,0
873,The Wolf of Wall Street,1,0.0,0,0,0
874,Dallas Buyers Club,1,0.0,0,0,0
875,Blue Jasmine,1,0.0,0,0,0
876,August: Osage County,1,0.0,0,0,0
877,Nebraska,1,0.0,0,0,0
878,The Judge,1,0.0,0,0,0
879,Boyhood,1,0.0,0,0,0
880,Birdman or (The Unexpected Virtue of Ignorance),1,0.0,0,0,0
881,Foxcatcher,1,0.0,0,0,0
882,Whiplash,1,0.0,0,0,0
883,Wild,1,0.0,0,0,0
884,The Imitation Game,1,0.0,0,0,0
885,Into the Woods,1,0.0,0,0,0
886,The Big Short,1,0.0,0,0,0
887,The Revenant,1,0.0,0,0,0
888,Spotlight,1,0.0,0,0,0
889,Bridge of Spies,1,0.0,0,0,0
890,Creed,1,0.0,0,0,0
891,The Hateful Eight,1,0.0,0,0,0
892,Carol,1,0.0,0,0,0
893,The Danish Girl,1,0.0,0,0,0
894,Steve Jobs,1,0.0,0,0,0

In [96]:
arr_awards_one = [0] * len(arr_film_one)
for i in range(0, len(arr_film_one)):
    arr_awards_one[i]+=actor_awards[actor_awards == arr_film_one[i]].shape[0]

arr_awards_zero = list(arr_awards_one)
for i in range(0, len(total_movies)-len(arr_film_one)):
    arr_awards_zero.append(0)

In [ ]:
col_awards_one = pd.DataFrame({'actor_awards': arr_awards_one})
col_film_one = pd.DataFrame({'film': arr_film_one})
df_actor_awards_one = pd.concat([col_awards_one, col_film_one],axis = 1)
df_actor_awards_one

In [ ]:
col_awards_zero = pd.DataFrame({'actor_awards': arr_awards_zero})
col_film_zero = pd.DataFrame({'film': arr_film_zero})
df_actor_awards_zero = pd.concat([col_awards_zero, col_film_zero],axis = 1)
df_actor_awards_zero